### ISSUE TITLE
autologin in account

### ISSUE THREAD

**Issue by jslby** [FydeOS/chromium_os_for_raspberry_pi#13]
Hello. Thx for you work.
I don now, how i can autologin in my google account in you OS.
Maybe you can help me

**Comment by fydeos-alpha** [comment]
It sounds like you are talking about "kiosk mode" offered as a paid feature in Chrome OS. Unfortunately without an active Enterprise GSuite account with Chrome Device Management feature, it's unable to accomplish what you after.
