### ISSUE TITLE
Raspberry Official 7" Touchscreen support

### ISSUE THREAD

**Issue by rideorgtfo** [FydeOS/chromium_os_for_raspberry_pi#2]
Touchscreen always black on [R70](https://github.com/FydeOS/chromium_os_for_raspberry_pi/tree/r70) build. I try plug and unplug hdmi, but it doesnot help.
But on [R68](https://github.com/FydeOS/chromium_os_for_raspberry_pi/tree/r68) it start itself, out-of-box, without hdmi manipulation.
How can I start it on R70?

**Comment by puccaso** [comment]
i would also love a resolution for this!
same issue here

**Comment by nmcain** [comment]
Perhaps we could merge the drivers for the screen into chrome os 70?

**Comment by yunshansimon** [comment]
Can you provide `/var/log/message`? Chromium OS for rpi3 is based on RPI official kernel with official configure. You can compile the kernel yourself and copy it to sd card.

**Comment by mac-user669** [comment]
I haven't installed FydeOS yet, but I have an Rpi 3b+ and the official 7 inch touchscreen. Has this issue been resolved? I can test, if need be

**Comment by puccaso** [comment]
> Can you provide `/var/log/message`? Chromium OS for rpi3 is based on RPI official kernel with official configure. You can compile the kernel yourself and copy it to sd card.

Interesting.. Could we try the #gentoo kernel? Any blobs we should know about?

**Comment by fydeos-alpha** [comment]
Bulk closure of dated issues

**Comment by MarcKarasek** [comment]
Has this been resolved?

**Comment by ankorez** [comment]
hello same issue here i have rollback to r68 :(
