### ISSUE TITLE
Password for chronos can't be changed.

### ISSUE THREAD

**Issue by pcs3rd** [FydeOS/chromium_os_for_raspberry_pi#24]
When using `passwd` in cros to change the password for `chronos`, passwd returns  
`passwd: Authentication token lock busy`
This prevents people from securing their devices... By not being able to change "well known credentials"

**Comment by fydeos-alpha** [comment]
by issuing `passwd`, try `sudo mount -o remount rw /`

**Comment by danielgoldbach68** [comment]
i am unable to change my sudo password 
![Screenshot (64)](https://user-images.githubusercontent.com/52566328/60838107-3d92b000-a1ca-11e9-975a-d11c10dda9c0.png)
