### ISSUE TITLE
autologin support?

### ISSUE THREAD

**Issue by xinyuwufei** [FydeOS/chromium_os_for_raspberry_pi#26]
Hi,
Thanks for the great work !
Im wondering is there a way to auto login the os? or Prevent turn off after 7-8mins on login page?
I found a [reference](https://chromium.googlesource.com/chromiumos/overlays/chromiumos-overlay/+/master/chromeos-base/autologin/files/init/autologin.conf) for chromium os

**Comment by blazerfanbc** [comment]
+1 this would be extremely useful

**Comment by fydeos-alpha** [comment]
The purpose of this project is to let people build and customise Chromium OS on Raspberry Pi devices, we will only release vanilla Chromium OS. If you wish to alter Chromium OS tailored to your needs, you should follow the README and build your own.
