### ISSUE TITLE
Developer mode

### ISSUE THREAD

**Issue by ShalokShalom** [FydeOS/chromium_os_for_raspberry_pi#28]
Hi 🤗 

Is there a method to enable the developer mode in order to install apps like this:

https://code.headmelted.com/

**Comment by nmcain** [comment]
Developer mode is already enabled, you can try crouton, but performance isn't great.

**Comment by ShalokShalom** [comment]
I tried to install https://chrome.google.com/webstore/detail/crouton-integration/gcpneefbbnfalgjniomfjknbcgkbijom while no installation button appears.

**Comment by ShalokShalom** [comment]
What is with the official Linux support by Google: 

![Screenshot_20190618_183953](https://user-images.githubusercontent.com/6344099/59702768-c7b5ad00-91f8-11e9-9e25-003359b86351.png)

**Comment by fydeos-alpha** [comment]
@ShalokShalom that's Linux subsystem that you were referring to, due to the hardware performance capability we don't have plans to include this.
