### ISSUE TITLE
Slack

### ISSUE THREAD

**Issue by ShalokShalom** [FydeOS/chromium_os_for_raspberry_pi#29]
This is what I get here when I click on your invitation link; 

![Screenshot 2019-06-17 at 08 12 07](https://user-images.githubusercontent.com/6344099/59615625-ae690f80-90d7-11e9-8227-9e14489b64f2.png)

I see no sign to actually register myself.

**Comment by nmcain** [comment]
you log in with slack and it does it automatically

**Comment by ShalokShalom** [comment]
No one logs in Slack. Every Slack channel has its own invitation. And its own password/username by that.

**Comment by fydeos-alpha** [comment]
If Slack isn't working for you, try our telegram group.
