### ISSUE TITLE
Dim screen when inactive

### ISSUE THREAD

**Issue by rideorgtfo** [FydeOS/chromium_os_for_raspberry_pi#3]
I tried set brightness of display with 
```
backlight_tool --set_brightness=xx //Work
```
Its work.
But when I try set power policy
```
set_power_policy --ac_screen_dim_delay=xx //Dont work
```
Nothing happens. How I can dim screen by inactive delay?

**Comment by yunshansimon** [comment]
Try to create a file named "ac_screen_dim_delay" at "/usr/share/power_manager/board_specific", xx as the content of the file.

**Comment by fydeos-alpha** [comment]
bulk closure of dated issues
