### ISSUE TITLE
Plugins

### ISSUE THREAD

**Issue by ShalokShalom** [FydeOS/chromium_os_for_raspberry_pi#30]
How is there no mention at all about Chrome plugins?

I see zero on the homepage and here in the Readme. 

I guess it is currently unsupported?

**Comment by nmcain** [comment]
extensions are supported unless they require a DRM, which google is legally unable to license.

**Comment by ShalokShalom** [comment]
I have tried several ones, including uBlock Origin, which is an open source app.

**Comment by ShalokShalom** [comment]
Nothing works and you close this issue?

Is this the quality control in this project?

**Comment by fydeos-alpha** [comment]
My understanding to your original question was about "Were plugins supported in Chromium OS for Raspberry Pi", which was well answered.

If you wished to report things don't work on your setup, it'd be helpful to rephrase with focuses on the issue itself and providing more information / screenshot / logfile will always help. Spreading FUD won't.

**Comment by ShalokShalom** [comment]
My second comment means that I tried them and it was not working. 

That there is no documentation about whatever they are working or not, is still its own issue. 

Pointing out a documentation issue is no FUD, it is part of the development.
