### ISSUE TITLE
Chromium OS can not start ?!

### ISSUE THREAD

**Issue by thanhecoz** [FydeOS/chromium_os_for_raspberry_pi#31]
Please help me !
I have a Raspberry Pi 3B and wanna install Chromium OS. (I connect to HDMI montor 10 inches) 
I download image (chromiumos_image_r72.img.xz) and flash into SD...
But it don't response when starting power the Raspberry Pi >> nothing display in the screen.

Please help me solve the problem.
Thks a lot.

**Comment by wintercicada-xyz** [comment]
Have you extract the image first?You should flash the .img file.

**Comment by fydeos-alpha** [comment]
bulk closure of dated/unreproducible issues
