### ISSUE TITLE
Airbar with chromium

### ISSUE THREAD

**Issue by anbu369** [FydeOS/chromium_os_for_raspberry_pi#32]
Hi,

I am planning to use [Airbar](https://air.bar/) with chromium. I connected it to the rpi's usb and the touch works perfectly on using android on pi and raspbian but on chromium, the screen goes black as soon as i connect the touchbar. seems like other people have problem with touchscreens as well. any help on this?

PS. Airbar is detected as a HID touchscreen device in windows.

**Comment by fydeos-alpha** [comment]
we don't own one of these, if you can't provide more meaningful info or logs, it's unlikely that we can be any helpful.
