### ISSUE TITLE
Raspberry Pi 3b+ black screen after boot.

### ISSUE THREAD

**Issue by filipton12** [FydeOS/chromium_os_for_raspberry_pi#34]
HI!
If i flash image to usb and i boot rpi i have a rainbow screen for 5 seconds, after rainbow screen i have black screen. I tried older version but i have this same problem. How can i fix it?

**Comment by fydeos-alpha** [comment]
we can't reproduce the issue you mentioned here. The rainbow screen is normal and expected. Consider changing a new SD card or a new power source see if it helps.

If you can provide more meaningful info or serial logs showing where it failed, it's unlikely that we can be any more helpful.

**Comment by kondziu95** [comment]
I had same problem. In my case it occured when i tried to boot system from usb stick. Boot from sd card solved this problem.
