### ISSUE TITLE
Enterprise Enrollement failed (Failed to determine device ID)

### ISSUE THREAD

**Issue by RedXTaz** [FydeOS/chromium_os_for_raspberry_pi#37]
Hi, 

I trying to enroll my Raspberry Pi4, but i'm getting "Oops! The system failed to determine device identifiers for this device." I tries to play with write-machine-info, but without success. Any idea?

Thanks

**Comment by fydeos-alpha** [comment]
It's a feature that we have not implemented

**Comment by lewisdonofrio** [comment]
We will need AirWatch/Intelligent hub/MDM Agent if this is to be used in NAC (Network Access Control) environments.

**Comment by fydeos-alpha** [comment]
with the added vpd support, Google Enterprise Enrollment should work.
