### ISSUE TITLE
Make it more clear there are prebuilt disk images in the readme

### ISSUE THREAD

**Issue by mrjohnc** [FydeOS/chromium_os_for_raspberry_pi#5]
From the current instructions it appears as though you need a lot of skills to install Chromium OS on a RP, however it looks like prebuilt images are available in the 'releases' tab, it would be really helpful if there was a note at the top of the readme that made this more clear

Thanks very much for working on this

**Comment by fydeos-alpha** [comment]
Accepted, thank you.
