### ISSUE TITLE
Bluetooth Issues

### ISSUE THREAD

**Issue by andras123** [FydeOS/chromium_os_for_raspberry_pi#8]
Can't turn on bluetooth, the button is greyed out. No idea what to do (tried turning it off and on)
![image](https://user-images.githubusercontent.com/5251412/51076967-cb6c6300-169f-11e9-8047-e1a09a8d7839.png)

**Comment by yunshansimon** [comment]
Please post the `dmesg`

**Comment by andras123** [comment]
It solved itself somehow after I restarted it a couple of times later
